#### Load TensorFlow and Enable Eager Execution

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

In [3]:
from sklearn.preprocessing import Normalizer

#### Load Data

In [4]:
(train_x, train_y),(_,_) = tf.keras.datasets.boston_housing.load_data(test_split=0)

57344/57026 [==============================] - 0s 4us/step


In [5]:
train_x[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
train_x = train_x.astype('float32')
train_y = train_y.astype('float32')

In [7]:
train_x.shape

(506, 13)

In [8]:
train_y.shape

(506,)

In [9]:
transformer = Normalizer()
train_x = transformer.fit_transform(train_x)

In [10]:
train_x[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945358, 0.00778265, 0.00782786, 0.60078794,
       0.04109624, 0.776719  , 0.03663436], dtype=float32)

#### Build Model

Define Weights and Bias

In [11]:
#We are initializing weights and Bias with Zero
w = tf.zeros(shape=(13,1))
b = tf.zeros(shape=(1))

Define a function to calculate prediction

In [12]:
def prediction(x, w, b):
    
    xw_matmul = tf.matmul(x, w)
    y = tf.add(xw_matmul, b)
    
    return y

Function to calculate Loss (Mean Squared Error)

In [13]:
def loss(y_actual, y_predicted):
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    
    return avg

Function to train the Model

1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate



In [14]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

#### Start Training

In [15]:
for i in range(100):
    
    w, b = train(train_x, train_y, w, b)
    print('Current Loss on iteration', i, loss(train_y, prediction(train_x, w, b)).numpy())

Current Loss on iteration 0 553.7515
Current Loss on iteration 1 518.2617
Current Loss on iteration 2 485.45786
Current Loss on iteration 3 455.1365
Current Loss on iteration 4 427.1098
Current Loss on iteration 5 401.20413
Current Loss on iteration 6 377.25897
Current Loss on iteration 7 355.12595
Current Loss on iteration 8 334.66788
Current Loss on iteration 9 315.75803
Current Loss on iteration 10 298.27924
Current Loss on iteration 11 282.1232
Current Loss on iteration 12 267.1898
Current Loss on iteration 13 253.38652
Current Loss on iteration 14 240.62787
Current Loss on iteration 15 228.83472
Current Loss on iteration 16 217.93405
Current Loss on iteration 17 207.8583
Current Loss on iteration 18 198.54506
Current Loss on iteration 19 189.9366
Current Loss on iteration 20 181.97958
Current Loss on iteration 21 174.62473
Current Loss on iteration 22 167.82645
Current Loss on iteration 23 161.54263
Current Loss on iteration 24 155.73434
Current Loss on iteration 25 150.36557
Curr

In [16]:
#Check Weights and Bias
print('Weights:\n', w.numpy())
print('Bias:\n',b.numpy())

Weights:
 [[6.27857521e-02]
 [2.58572161e-01]
 [2.17821732e-01]
 [1.46146421e-03]
 [1.13587305e-02]
 [1.31812558e-01]
 [1.38818800e+00]
 [8.23873580e-02]
 [1.76484972e-01]
 [7.99328279e+00]
 [3.82081807e-01]
 [7.41107655e+00]
 [2.53885090e-01]]
Bias:
 [11.476417]
